# Site settings
name: Victor Liang Zheng
email: victorliangzheng88@gmail.com
url: https://victorliangzheng88.github.io/jekyll-theme-blogfolio/
description: "A blog and a portfolio"
author: "Victor Liang Zheng"
title: "Blog"
permalink: pretty
baseurl: /Blog

# social
github:
  username: victorliangzheng88

twitter:
  username: VictorLiangZ1
