# Site settings
name: name
email: email
url: url
description: "A blog and a portfolio"
author: "author"
title: "Blog"
permalink: pretty
baseurl: /Blog

# social
github:
  username: username

twitter:
  username: username
